 var extensionConstants = [
	  { name: "MAX_COLOR_ATTACHMENTS_WEBGL", enum: 0x8CDF, expectedFn: function(v) { return v > 0; }, passMsg: " should be > 0"},
	  { name: "MAX_DRAW_BUFFERS_WEBGL",      enum: 0x8824, expectedFn: function(v) { return v > 0; }, passMsg: " should be > 0"},

	  { name: "COLOR_ATTACHMENT0_WEBGL",     enum: 0x8CE0, },
	  { name: "COLOR_ATTACHMENT1_WEBGL",     enum: 0x8CE1, },
	  { name: "COLOR_ATTACHMENT2_WEBGL",     enum: 0x8CE2, },
	  { name: "COLOR_ATTACHMENT3_WEBGL",     enum: 0x8CE3, },
	  { name: "COLOR_ATTACHMENT4_WEBGL",     enum: 0x8CE4, },
	  { name: "COLOR_ATTACHMENT5_WEBGL",     enum: 0x8CE5, },
	  { name: "COLOR_ATTACHMENT6_WEBGL",     enum: 0x8CE6, },
	  { name: "COLOR_ATTACHMENT7_WEBGL",     enum: 0x8CE7, },
	  { name: "COLOR_ATTACHMENT8_WEBGL",     enum: 0x8CE8, },
	  { name: "COLOR_ATTACHMENT9_WEBGL",     enum: 0x8CE9, },
	  { name: "COLOR_ATTACHMENT10_WEBGL",    enum: 0x8CEA, },
	  { name: "COLOR_ATTACHMENT11_WEBGL",    enum: 0x8CEB, },
	  { name: "COLOR_ATTACHMENT12_WEBGL",    enum: 0x8CEC, },
	  { name: "COLOR_ATTACHMENT13_WEBGL",    enum: 0x8CED, },
	  { name: "COLOR_ATTACHMENT14_WEBGL",    enum: 0x8CEE, },
	  { name: "COLOR_ATTACHMENT15_WEBGL",    enum: 0x8CEF, },

	  { name: "DRAW_BUFFER0_WEBGL",          enum: 0x8825, },
	  { name: "DRAW_BUFFER1_WEBGL",          enum: 0x8826, },
	  { name: "DRAW_BUFFER2_WEBGL",          enum: 0x8827, },
	  { name: "DRAW_BUFFER3_WEBGL",          enum: 0x8828, },
	  { name: "DRAW_BUFFER4_WEBGL",          enum: 0x8829, },
	  { name: "DRAW_BUFFER5_WEBGL",          enum: 0x882A, },
	  { name: "DRAW_BUFFER6_WEBGL",          enum: 0x882B, },
	  { name: "DRAW_BUFFER7_WEBGL",          enum: 0x882C, },
	  { name: "DRAW_BUFFER8_WEBGL",          enum: 0x882D, },
	  { name: "DRAW_BUFFER9_WEBGL",          enum: 0x882E, },
	  { name: "DRAW_BUFFER10_WEBGL",         enum: 0x882F, },
	  { name: "DRAW_BUFFER11_WEBGL",         enum: 0x8830, },
	  { name: "DRAW_BUFFER12_WEBGL",         enum: 0x8831, },
	  { name: "DRAW_BUFFER13_WEBGL",         enum: 0x8832, },
	  { name: "DRAW_BUFFER14_WEBGL",         enum: 0x8833, },
	  { name: "DRAW_BUFFER15_WEBGL",         enum: 0x8834, },
	];